--生成日期 2012-03-07
SET IDENTITY_INSERT [tbl_SysProvince] ON

INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 1,1,'北京市')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 2,1,'天津市')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 3,1,'河北省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 4,1,'山西省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 5,1,'内蒙古自治区')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 6,1,'辽宁省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 7,1,'吉林省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 8,1,'黑龙江省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 9,1,'上海市')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 10,1,'江苏省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 11,1,'浙江省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 12,1,'安徽省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 13,1,'福建省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 14,1,'江西省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 15,1,'山东省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 16,1,'河南省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 17,1,'湖北省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 18,1,'湖南省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 19,1,'广东省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 20,1,'广西壮族自治区')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 21,1,'海南省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 22,1,'重庆市')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 23,1,'四川省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 24,1,'贵州省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 25,1,'云南省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 26,1,'西藏自治区')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 27,1,'陕西省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 28,1,'甘肃省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 29,1,'青海省')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 30,1,'宁夏回族自治区')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 31,1,'新疆维吾尔自治区')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 32,1,'香港特别行政区')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 33,1,'澳门特别行政区')
INSERT [tbl_SysProvince] ([ProvinceId],[CountryId],[Name]) VALUES ( 34,1,'台湾省')

SET IDENTITY_INSERT [tbl_SysProvince] OFF
