//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5466 版自动生成。
// 
#pragma warning disable 1591

namespace EyouSoft.BackgroundServices.SmsApi {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SmsApiSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiSoapHeader))]
    public partial class SmsApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SmsApiSoapHeader smsApiSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback SendMessageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SmsApi() {
            this.Url = global::EyouSoft.BackgroundServices.Properties.Settings.Default.EyouSoft_BackgroundServices_SmsApi_SmsApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SmsApiSoapHeader SmsApiSoapHeaderValue {
            get {
                return this.smsApiSoapHeaderValueField;
            }
            set {
                this.smsApiSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SmsApiSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MSendResult SendMessage(MSendMessage message) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        message});
            return ((MSendResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(MSendMessage message) {
            this.SendMessageAsync(message, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(MSendMessage message, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        message}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class SmsApiSoapHeader : ApiSoapHeader {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SmsApiSoapHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ApiSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string secretKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string SecretKey {
            get {
                return this.secretKeyField;
            }
            set {
                this.secretKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MSendResult {
        
        private bool isSucceedField;
        
        private string errorMessageField;
        
        private decimal countFeeField;
        
        private decimal accountMoneyField;
        
        private int mobileNumberCountField;
        
        private int phsNumberCountField;
        
        private int successCountField;
        
        private int phsSuccessCountField;
        
        private int factCountField;
        
        private int phsFactCountField;
        
        private string smsCenterPlanIdField;
        
        /// <remarks/>
        public bool IsSucceed {
            get {
                return this.isSucceedField;
            }
            set {
                this.isSucceedField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public decimal CountFee {
            get {
                return this.countFeeField;
            }
            set {
                this.countFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal AccountMoney {
            get {
                return this.accountMoneyField;
            }
            set {
                this.accountMoneyField = value;
            }
        }
        
        /// <remarks/>
        public int MobileNumberCount {
            get {
                return this.mobileNumberCountField;
            }
            set {
                this.mobileNumberCountField = value;
            }
        }
        
        /// <remarks/>
        public int PhsNumberCount {
            get {
                return this.phsNumberCountField;
            }
            set {
                this.phsNumberCountField = value;
            }
        }
        
        /// <remarks/>
        public int SuccessCount {
            get {
                return this.successCountField;
            }
            set {
                this.successCountField = value;
            }
        }
        
        /// <remarks/>
        public int PhsSuccessCount {
            get {
                return this.phsSuccessCountField;
            }
            set {
                this.phsSuccessCountField = value;
            }
        }
        
        /// <remarks/>
        public int FactCount {
            get {
                return this.factCountField;
            }
            set {
                this.factCountField = value;
            }
        }
        
        /// <remarks/>
        public int PhsFactCount {
            get {
                return this.phsFactCountField;
            }
            set {
                this.phsFactCountField = value;
            }
        }
        
        /// <remarks/>
        public string SmsCenterPlanId {
            get {
                return this.smsCenterPlanIdField;
            }
            set {
                this.smsCenterPlanIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MSmsNumber {
        
        private string codeField;
        
        private MobileType typeField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public MobileType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MobileType {
        
        /// <remarks/>
        Mobiel,
        
        /// <remarks/>
        Phs,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MSendMessage {
        
        private string companyIdField;
        
        private string userIdField;
        
        private string userFullNameField;
        
        private string smsContentField;
        
        private System.DateTime sendTimeField;
        
        private MSmsNumber[] mobilesField;
        
        private SendType sendTypeField;
        
        private int sendChannelField;
        
        private LeiXing leiXingField;
        
        /// <remarks/>
        public string CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string SmsContent {
            get {
                return this.smsContentField;
            }
            set {
                this.smsContentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
            }
        }
        
        /// <remarks/>
        public MSmsNumber[] Mobiles {
            get {
                return this.mobilesField;
            }
            set {
                this.mobilesField = value;
            }
        }
        
        /// <remarks/>
        public SendType SendType {
            get {
                return this.sendTypeField;
            }
            set {
                this.sendTypeField = value;
            }
        }
        
        /// <remarks/>
        public int SendChannel {
            get {
                return this.sendChannelField;
            }
            set {
                this.sendChannelField = value;
            }
        }
        
        /// <remarks/>
        public LeiXing LeiXing {
            get {
                return this.leiXingField;
            }
            set {
                this.leiXingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SendType {
        
        /// <remarks/>
        直接发送,
        
        /// <remarks/>
        定时发送,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LeiXing {
        
        /// <remarks/>
        直接发送,
        
        /// <remarks/>
        定时发送,
        
        /// <remarks/>
        进店提醒,
        
        /// <remarks/>
        出团通知,
        
        /// <remarks/>
        回团通知,
        
        /// <remarks/>
        生日提醒,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendMessageCompletedEventHandler(object sender, SendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MSendResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MSendResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591