//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3649
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _string {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _string() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.string", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为所有资源查找重写当前线程的 CurrentUICulture 属性，
        ///   方法是使用此强类型资源类。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        internal static string 上移 {
            get {
                return ResourceManager.GetString("上移", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        internal static string 下移 {
            get {
                return ResourceManager.GetString("下移", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入的密码不一致 的本地化字符串。
        /// </summary>
        internal static string 两次输入的密码不一致 {
            get {
                return ResourceManager.GetString("两次输入的密码不一致", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个性服务要求 的本地化字符串。
        /// </summary>
        internal static string 个性服务要求 {
            get {
                return ResourceManager.GetString("个性服务要求", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中 的本地化字符串。
        /// </summary>
        internal static string 中 {
            get {
                return ResourceManager.GetString("中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中餐 的本地化字符串。
        /// </summary>
        internal static string 中餐 {
            get {
                return ResourceManager.GetString("中餐", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交通 的本地化字符串。
        /// </summary>
        internal static string 交通 {
            get {
                return ResourceManager.GetString("交通", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人数 的本地化字符串。
        /// </summary>
        internal static string 人数 {
            get {
                return ResourceManager.GetString("人数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格 的本地化字符串。
        /// </summary>
        internal static string 价格 {
            get {
                return ResourceManager.GetString("价格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住宿 的本地化字符串。
        /// </summary>
        internal static string 住宿 {
            get {
                return ResourceManager.GetString("住宿", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商名称 的本地化字符串。
        /// </summary>
        internal static string 供应商名称 {
            get {
                return ResourceManager.GetString("供应商名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string 保存 {
            get {
                return ResourceManager.GetString("保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存内容不能为空 的本地化字符串。
        /// </summary>
        internal static string 保存内容不能为空 {
            get {
                return ResourceManager.GetString("保存内容不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功 的本地化字符串。
        /// </summary>
        internal static string 修改成功 {
            get {
                return ResourceManager.GetString("修改成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改询价 的本地化字符串。
        /// </summary>
        internal static string 修改询价 {
            get {
                return ResourceManager.GetString("修改询价", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素 的本地化字符串。
        /// </summary>
        internal static string 像素 {
            get {
                return ResourceManager.GetString("像素", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 儿童 的本地化字符串。
        /// </summary>
        internal static string 儿童 {
            get {
                return ResourceManager.GetString("儿童", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 儿童价 的本地化字符串。
        /// </summary>
        internal static string 儿童价 {
            get {
                return ResourceManager.GetString("儿童价", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元/人 的本地化字符串。
        /// </summary>
        internal static string 元人 {
            get {
                return ResourceManager.GetString("元人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称 的本地化字符串。
        /// </summary>
        internal static string 公司名称 {
            get {
                return ResourceManager.GetString("公司名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告 的本地化字符串。
        /// </summary>
        internal static string 公告 {
            get {
                return ResourceManager.GetString("公告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string 关闭 {
            get {
                return ResourceManager.GetString("关闭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他费用 的本地化字符串。
        /// </summary>
        internal static string 其他费用 {
            get {
                return ResourceManager.GetString("其他费用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内宾 的本地化字符串。
        /// </summary>
        internal static string 内宾 {
            get {
                return ResourceManager.GetString("内宾", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减 的本地化字符串。
        /// </summary>
        internal static string 减 {
            get {
                return ResourceManager.GetString("减", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出团时间 的本地化字符串。
        /// </summary>
        internal static string 出团时间 {
            get {
                return ResourceManager.GetString("出团时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出团确认单 的本地化字符串。
        /// </summary>
        internal static string 出团确认单 {
            get {
                return ResourceManager.GetString("出团确认单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出团通知书 的本地化字符串。
        /// </summary>
        internal static string 出团通知书 {
            get {
                return ResourceManager.GetString("出团通知书", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string 删除 {
            get {
                return ResourceManager.GetString("删除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string 删除成功 {
            get {
                return ResourceManager.GetString("删除成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除询价 的本地化字符串。
        /// </summary>
        internal static string 删除询价 {
            get {
                return ResourceManager.GetString("删除询价", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除附件 的本地化字符串。
        /// </summary>
        internal static string 删除附件 {
            get {
                return ResourceManager.GetString("删除附件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加 的本地化字符串。
        /// </summary>
        internal static string 加 {
            get {
                return ResourceManager.GetString("加", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单价 的本地化字符串。
        /// </summary>
        internal static string 单价 {
            get {
                return ResourceManager.GetString("单价", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单房差 的本地化字符串。
        /// </summary>
        internal static string 单房差 {
            get {
                return ResourceManager.GetString("单房差", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 县区 的本地化字符串。
        /// </summary>
        internal static string 县区 {
            get {
                return ResourceManager.GetString("县区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参考菜单 的本地化字符串。
        /// </summary>
        internal static string 参考菜单 {
            get {
                return ResourceManager.GetString("参考菜单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布人 的本地化字符串。
        /// </summary>
        internal static string 发布人 {
            get {
                return ResourceManager.GetString("发布人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送失败 的本地化字符串。
        /// </summary>
        internal static string 发送失败 {
            get {
                return ResourceManager.GetString("发送失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送成功 的本地化字符串。
        /// </summary>
        internal static string 发送成功 {
            get {
                return ResourceManager.GetString("发送成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送邮件 的本地化字符串。
        /// </summary>
        internal static string 发送邮件 {
            get {
                return ResourceManager.GetString("发送邮件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消原因 的本地化字符串。
        /// </summary>
        internal static string 取消原因 {
            get {
                return ResourceManager.GetString("取消原因", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消报价 的本地化字符串。
        /// </summary>
        internal static string 取消报价 {
            get {
                return ResourceManager.GetString("取消报价", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能选择一个县区 的本地化字符串。
        /// </summary>
        internal static string 只能选择一个县区 {
            get {
                return ResourceManager.GetString("只能选择一个县区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能选择一个城市 的本地化字符串。
        /// </summary>
        internal static string 只能选择一个城市 {
            get {
                return ResourceManager.GetString("只能选择一个城市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能选择一行数据进行修改 的本地化字符串。
        /// </summary>
        internal static string 只能选择一行数据进行修改 {
            get {
                return ResourceManager.GetString("只能选择一行数据进行修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计金额 的本地化字符串。
        /// </summary>
        internal static string 合计金额 {
            get {
                return ResourceManager.GetString("合计金额", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同行价 的本地化字符串。
        /// </summary>
        internal static string 同行价 {
            get {
                return ResourceManager.GetString("同行价", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 咨询时间 的本地化字符串。
        /// </summary>
        internal static string 咨询时间 {
            get {
                return ResourceManager.GetString("咨询时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 因当地法律或其他原因不能解析给出地址 的本地化字符串。
        /// </summary>
        internal static string 因当地法律或其他原因不能解析给出地址 {
            get {
                return ResourceManager.GetString("因当地法律或其他原因不能解析给出地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 团号 的本地化字符串。
        /// </summary>
        internal static string 团号 {
            get {
                return ResourceManager.GetString("团号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 团型 的本地化字符串。
        /// </summary>
        internal static string 团型 {
            get {
                return ResourceManager.GetString("团型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 团队 的本地化字符串。
        /// </summary>
        internal static string 团队 {
            get {
                return ResourceManager.GetString("团队", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家 的本地化字符串。
        /// </summary>
        internal static string 国家 {
            get {
                return ResourceManager.GetString("国家", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家 地区 的本地化字符串。
        /// </summary>
        internal static string 国家地区 {
            get {
                return ResourceManager.GetString("国家地区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国籍 的本地化字符串。
        /// </summary>
        internal static string 国籍 {
            get {
                return ResourceManager.GetString("国籍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /images/delimg.gif 的本地化字符串。
        /// </summary>
        internal static string 图片删除链接 {
            get {
                return ResourceManager.GetString("图片删除链接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /images/charuimg.gif 的本地化字符串。
        /// </summary>
        internal static string 图片插入链接 {
            get {
                return ResourceManager.GetString("图片插入链接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /images/fx-images/searchbg.gif 的本地化字符串。
        /// </summary>
        internal static string 图片搜索链接 {
            get {
                return ResourceManager.GetString("图片搜索链接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /images/addimg.gif 的本地化字符串。
        /// </summary>
        internal static string 图片添加链接 {
            get {
                return ResourceManager.GetString("图片添加链接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /images/xuanyong.gif 的本地化字符串。
        /// </summary>
        internal static string 图片选用链接 {
            get {
                return ResourceManager.GetString("图片选用链接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图 的本地化字符串。
        /// </summary>
        internal static string 地图 {
            get {
                return ResourceManager.GetString("地图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市 的本地化字符串。
        /// </summary>
        internal static string 城市 {
            get {
                return ResourceManager.GetString("城市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加日程 的本地化字符串。
        /// </summary>
        internal static string 增加日程 {
            get {
                return ResourceManager.GetString("增加日程", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string 备注 {
            get {
                return ResourceManager.GetString("备注", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外宾 的本地化字符串。
        /// </summary>
        internal static string 外宾 {
            get {
                return ResourceManager.GetString("外宾", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天 的本地化字符串。
        /// </summary>
        internal static string 天 {
            get {
                return ResourceManager.GetString("天", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天数 的本地化字符串。
        /// </summary>
        internal static string 天数 {
            get {
                return ResourceManager.GetString("天数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如不修改请置空 的本地化字符串。
        /// </summary>
        internal static string 如不修改请置空 {
            get {
                return ResourceManager.GetString("如不修改请置空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        internal static string 字体 {
            get {
                return ResourceManager.GetString("字体", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客源单位 的本地化字符串。
        /// </summary>
        internal static string 客源单位 {
            get {
                return ResourceManager.GetString("客源单位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宾客类型 的本地化字符串。
        /// </summary>
        internal static string 宾客类型 {
            get {
                return ResourceManager.GetString("宾客类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string 密码 {
            get {
                return ResourceManager.GetString("密码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string 密码不能为空 {
            get {
                return ResourceManager.GetString("密码不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改失败 的本地化字符串。
        /// </summary>
        internal static string 密码修改失败 {
            get {
                return ResourceManager.GetString("密码修改失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改成功，正在跳转… 的本地化字符串。
        /// </summary>
        internal static string 密码修改成功 {
            get {
                return ResourceManager.GetString("密码修改成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入类库是指定的密钥有误 的本地化字符串。
        /// </summary>
        internal static string 导入类库是指定的密钥有误 {
            get {
                return ResourceManager.GetString("导入类库是指定的密钥有误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string 导出 {
            get {
                return ResourceManager.GetString("导出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小费 的本地化字符串。
        /// </summary>
        internal static string 小费 {
            get {
                return ResourceManager.GetString("小费", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小费名称 的本地化字符串。
        /// </summary>
        internal static string 小费名称 {
            get {
                return ResourceManager.GetString("小费名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已付金额 的本地化字符串。
        /// </summary>
        internal static string 已付金额 {
            get {
                return ResourceManager.GetString("已付金额", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经报价成功的数据不允许修改 的本地化字符串。
        /// </summary>
        internal static string 已经报价成功的数据不允许修改 {
            get {
                return ResourceManager.GetString("已经报价成功的数据不允许修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已结清 的本地化字符串。
        /// </summary>
        internal static string 已结清 {
            get {
                return ResourceManager.GetString("已结清", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已调整至最大字体 的本地化字符串。
        /// </summary>
        internal static string 已调整至最大字体 {
            get {
                return ResourceManager.GetString("已调整至最大字体", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已调整至最小字体 的本地化字符串。
        /// </summary>
        internal static string 已调整至最小字体 {
            get {
                return ResourceManager.GetString("已调整至最小字体", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平季价格 的本地化字符串。
        /// </summary>
        internal static string 平季价格 {
            get {
                return ResourceManager.GetString("平季价格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应付金额 的本地化字符串。
        /// </summary>
        internal static string 应付金额 {
            get {
                return ResourceManager.GetString("应付金额", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        internal static string 开始时间 {
            get {
                return ResourceManager.GetString("开始时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成人 的本地化字符串。
        /// </summary>
        internal static string 成人 {
            get {
                return ResourceManager.GetString("成人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成人价 的本地化字符串。
        /// </summary>
        internal static string 成人价 {
            get {
                return ResourceManager.GetString("成人价", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的订单 的本地化字符串。
        /// </summary>
        internal static string 我的订单 {
            get {
                return ResourceManager.GetString("我的订单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或 的本地化字符串。
        /// </summary>
        internal static string 或 {
            get {
                return ResourceManager.GetString("或", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截止时间 的本地化字符串。
        /// </summary>
        internal static string 截止时间 {
            get {
                return ResourceManager.GetString("截止时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        internal static string 打印 {
            get {
                return ResourceManager.GetString("打印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印设置 的本地化字符串。
        /// </summary>
        internal static string 打印设置 {
            get {
                return ResourceManager.GetString("打印设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印设置失败！ 的本地化字符串。
        /// </summary>
        internal static string 打印设置失败 {
            get {
                return ResourceManager.GetString("打印设置失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印设置成功，正在跳转… 的本地化字符串。
        /// </summary>
        internal static string 打印设置成功 {
            get {
                return ResourceManager.GetString("打印设置成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报价单 的本地化字符串。
        /// </summary>
        internal static string 报价单 {
            get {
                return ResourceManager.GetString("报价单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报价备注 的本地化字符串。
        /// </summary>
        internal static string 报价备注 {
            get {
                return ResourceManager.GetString("报价备注", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报价成功 的本地化字符串。
        /// </summary>
        internal static string 报价成功 {
            get {
                return ResourceManager.GetString("报价成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报价状态 的本地化字符串。
        /// </summary>
        internal static string 报价状态 {
            get {
                return ResourceManager.GetString("报价状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报名 的本地化字符串。
        /// </summary>
        internal static string 报名 {
            get {
                return ResourceManager.GetString("报名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抵达城市 的本地化字符串。
        /// </summary>
        internal static string 抵达城市 {
            get {
                return ResourceManager.GetString("抵达城市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抵达日期 的本地化字符串。
        /// </summary>
        internal static string 抵达日期 {
            get {
                return ResourceManager.GetString("抵达日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交中… 的本地化字符串。
        /// </summary>
        internal static string 提交中 {
            get {
                return ResourceManager.GetString("提交中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入 的本地化字符串。
        /// </summary>
        internal static string 插入 {
            get {
                return ResourceManager.GetString("插入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string 搜索 {
            get {
                return ResourceManager.GetString("搜索", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string 操作 {
            get {
                return ResourceManager.GetString("操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string 操作失败 {
            get {
                return ResourceManager.GetString("操作失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收客计划 的本地化字符串。
        /// </summary>
        internal static string 收客计划 {
            get {
                return ResourceManager.GetString("收客计划", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 散客 的本地化字符串。
        /// </summary>
        internal static string 散客 {
            get {
                return ResourceManager.GetString("散客", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增成功 的本地化字符串。
        /// </summary>
        internal static string 新增成功 {
            get {
                return ResourceManager.GetString("新增成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增询价 的本地化字符串。
        /// </summary>
        internal static string 新增询价 {
            get {
                return ResourceManager.GetString("新增询价", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除已经报价成功的数据 的本地化字符串。
        /// </summary>
        internal static string 无法删除已经报价成功的数据 {
            get {
                return ResourceManager.GetString("无法删除已经报价成功的数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        internal static string 日期 {
            get {
                return ResourceManager.GetString("日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 早 的本地化字符串。
        /// </summary>
        internal static string 早 {
            get {
                return ResourceManager.GetString("早", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 早餐 的本地化字符串。
        /// </summary>
        internal static string 早餐 {
            get {
                return ResourceManager.GetString("早餐", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旺季价格 的本地化字符串。
        /// </summary>
        internal static string 旺季价格 {
            get {
                return ResourceManager.GetString("旺季价格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除? 的本地化字符串。
        /// </summary>
        internal static string 是否删除 {
            get {
                return ResourceManager.GetString("是否删除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否确定发送 的本地化字符串。
        /// </summary>
        internal static string 是否确定发送 {
            get {
                return ResourceManager.GetString("是否确定发送", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晚 的本地化字符串。
        /// </summary>
        internal static string 晚 {
            get {
                return ResourceManager.GetString("晚", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晚餐 的本地化字符串。
        /// </summary>
        internal static string 晚餐 {
            get {
                return ResourceManager.GetString("晚餐", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 景点 的本地化字符串。
        /// </summary>
        internal static string 景点 {
            get {
                return ResourceManager.GetString("景点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 景点名称 的本地化字符串。
        /// </summary>
        internal static string 景点名称 {
            get {
                return ResourceManager.GetString("景点名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无数据 的本地化字符串。
        /// </summary>
        internal static string 暂无数据 {
            get {
                return ResourceManager.GetString("暂无数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大行间距 的本地化字符串。
        /// </summary>
        internal static string 最大行间距 {
            get {
                return ResourceManager.GetString("最大行间距", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小行间距 的本地化字符串。
        /// </summary>
        internal static string 最小行间距 {
            get {
                return ResourceManager.GetString("最小行间距", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最少保留一行 的本地化字符串。
        /// </summary>
        internal static string 最少保留一行 {
            get {
                return ResourceManager.GetString("最少保留一行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器不能正确解析你输入的地址 的本地化字符串。
        /// </summary>
        internal static string 服务器不能正确解析你输入的地址 {
            get {
                return ResourceManager.GetString("服务器不能正确解析你输入的地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未付金额 的本地化字符串。
        /// </summary>
        internal static string 未付金额 {
            get {
                return ResourceManager.GetString("未付金额", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未匹配到城市 的本地化字符串。
        /// </summary>
        internal static string 未匹配到城市 {
            get {
                return ResourceManager.GetString("未匹配到城市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未报价成功 的本地化字符串。
        /// </summary>
        internal static string 未报价成功 {
            get {
                return ResourceManager.GetString("未报价成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未结清 的本地化字符串。
        /// </summary>
        internal static string 未结清 {
            get {
                return ResourceManager.GetString("未结清", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string 查看 {
            get {
                return ResourceManager.GetString("查看", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询地址未知 的本地化字符串。
        /// </summary>
        internal static string 查询地址未知 {
            get {
                return ResourceManager.GetString("查询地址未知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询太过频繁，超出密钥允许的查询次数 的本地化字符串。
        /// </summary>
        internal static string 查询太过频繁 {
            get {
                return ResourceManager.GetString("查询太过频繁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询条件（地址）不能为空 的本地化字符串。
        /// </summary>
        internal static string 查询条件不能为空 {
            get {
                return ResourceManager.GetString("查询条件不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载,请等待 的本地化字符串。
        /// </summary>
        internal static string 正在加载请等待 {
            get {
                return ResourceManager.GetString("正在加载请等待", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 淡季价格 的本地化字符串。
        /// </summary>
        internal static string 淡季价格 {
            get {
                return ResourceManager.GetString("淡季价格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        internal static string 清除 {
            get {
                return ResourceManager.GetString("清除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特推线路 的本地化字符串。
        /// </summary>
        internal static string 特推线路 {
            get {
                return ResourceManager.GetString("特推线路", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string 状态 {
            get {
                return ResourceManager.GetString("状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息 的本地化字符串。
        /// </summary>
        internal static string 用户信息 {
            get {
                return ResourceManager.GetString("用户信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string 用户名 {
            get {
                return ResourceManager.GetString("用户名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        internal static string 用户名不能为空 {
            get {
                return ResourceManager.GetString("用户名不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已存在 的本地化字符串。
        /// </summary>
        internal static string 用户名已存在 {
            get {
                return ResourceManager.GetString("用户名已存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码不正确 的本地化字符串。
        /// </summary>
        internal static string 用户名或密码不正确 {
            get {
                return ResourceManager.GetString("用户名或密码不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用餐 的本地化字符串。
        /// </summary>
        internal static string 用餐 {
            get {
                return ResourceManager.GetString("用餐", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆 的本地化字符串。
        /// </summary>
        internal static string 登陆 {
            get {
                return ResourceManager.GetString("登陆", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省份 的本地化字符串。
        /// </summary>
        internal static string 省份 {
            get {
                return ResourceManager.GetString("省份", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离开城市 的本地化字符串。
        /// </summary>
        internal static string 离开城市 {
            get {
                return ResourceManager.GetString("离开城市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离开日期 的本地化字符串。
        /// </summary>
        internal static string 离开日期 {
            get {
                return ResourceManager.GetString("离开日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 的本地化字符串。
        /// </summary>
        internal static string 第 {
            get {
                return ResourceManager.GetString("第", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简要行程单 的本地化字符串。
        /// </summary>
        internal static string 简要行程单 {
            get {
                return ResourceManager.GetString("简要行程单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string 系统设置 {
            get {
                return ResourceManager.GetString("系统设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线路区域 的本地化字符串。
        /// </summary>
        internal static string 线路区域 {
            get {
                return ResourceManager.GetString("线路区域", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线路名称 的本地化字符串。
        /// </summary>
        internal static string 线路名称 {
            get {
                return ResourceManager.GetString("线路名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算中心 的本地化字符串。
        /// </summary>
        internal static string 结算中心 {
            get {
                return ResourceManager.GetString("结算中心", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算价 的本地化字符串。
        /// </summary>
        internal static string 结算价 {
            get {
                return ResourceManager.GetString("结算价", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给出的两地之间无路可走或我们的现有的数据中缺少路线规划路线 的本地化字符串。
        /// </summary>
        internal static string 给出的两地之间无路可走或我们的现有的数据中缺少路线规划路线 {
            get {
                return ResourceManager.GetString("给出的两地之间无路可走或我们的现有的数据中缺少路线规划路线", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string 编号 {
            get {
                return ResourceManager.GetString("编号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自费项目 的本地化字符串。
        /// </summary>
        internal static string 自费项目 {
            get {
                return ResourceManager.GetString("自费项目", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航班/时间 的本地化字符串。
        /// </summary>
        internal static string 航班时间 {
            get {
                return ResourceManager.GetString("航班时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        internal static string 菜单 {
            get {
                return ResourceManager.GetString("菜单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行程中城市不能为空 的本地化字符串。
        /// </summary>
        internal static string 行程中城市不能为空 {
            get {
                return ResourceManager.GetString("行程中城市不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行程亮点 的本地化字符串。
        /// </summary>
        internal static string 行程亮点 {
            get {
                return ResourceManager.GetString("行程亮点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行程单 的本地化字符串。
        /// </summary>
        internal static string 行程单 {
            get {
                return ResourceManager.GetString("行程单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行程备注 的本地化字符串。
        /// </summary>
        internal static string 行程备注 {
            get {
                return ResourceManager.GetString("行程备注", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行程安排 的本地化字符串。
        /// </summary>
        internal static string 行程安排 {
            get {
                return ResourceManager.GetString("行程安排", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行间距 的本地化字符串。
        /// </summary>
        internal static string 行间距 {
            get {
                return ResourceManager.GetString("行间距", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计调员 的本地化字符串。
        /// </summary>
        internal static string 计调员 {
            get {
                return ResourceManager.GetString("计调员", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计调安排确认单 的本地化字符串。
        /// </summary>
        internal static string 计调安排确认单 {
            get {
                return ResourceManager.GetString("计调安排确认单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单状态 的本地化字符串。
        /// </summary>
        internal static string 订单状态 {
            get {
                return ResourceManager.GetString("订单状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住用户名 的本地化字符串。
        /// </summary>
        internal static string 记住用户名 {
            get {
                return ResourceManager.GetString("记住用户名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询价中心 的本地化字符串。
        /// </summary>
        internal static string 询价中心 {
            get {
                return ResourceManager.GetString("询价中心", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询价日期 的本地化字符串。
        /// </summary>
        internal static string 询价日期 {
            get {
                return ResourceManager.GetString("询价日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询价日期不能为空 的本地化字符串。
        /// </summary>
        internal static string 询价日期不能为空 {
            get {
                return ResourceManager.GetString("询价日期不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询价编号 的本地化字符串。
        /// </summary>
        internal static string 询价编号 {
            get {
                return ResourceManager.GetString("询价编号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细行程 的本地化字符串。
        /// </summary>
        internal static string 详细行程 {
            get {
                return ResourceManager.GetString("详细行程", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细行程单 的本地化字符串。
        /// </summary>
        internal static string 详细行程单 {
            get {
                return ResourceManager.GetString("详细行程单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string 语言 {
            get {
                return ResourceManager.GetString("语言", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择国家 的本地化字符串。
        /// </summary>
        internal static string 请先选择国家 {
            get {
                return ResourceManager.GetString("请先选择国家", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择城市 的本地化字符串。
        /// </summary>
        internal static string 请先选择城市 {
            get {
                return ResourceManager.GetString("请先选择城市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入抵达日期 的本地化字符串。
        /// </summary>
        internal static string 请输入抵达日期 {
            get {
                return ResourceManager.GetString("请输入抵达日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入最大成人数 的本地化字符串。
        /// </summary>
        internal static string 请输入最大成人数 {
            get {
                return ResourceManager.GetString("请输入最大成人数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入最小成人数 的本地化字符串。
        /// </summary>
        internal static string 请输入最小成人数 {
            get {
                return ResourceManager.GetString("请输入最小成人数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的天数 的本地化字符串。
        /// </summary>
        internal static string 请输入正确的天数 {
            get {
                return ResourceManager.GetString("请输入正确的天数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的赠送金额 的本地化字符串。
        /// </summary>
        internal static string 请输入正确的赠送金额 {
            get {
                return ResourceManager.GetString("请输入正确的赠送金额", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的邮箱地址 的本地化字符串。
        /// </summary>
        internal static string 请输入正确的邮箱地址 {
            get {
                return ResourceManager.GetString("请输入正确的邮箱地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的金额 的本地化字符串。
        /// </summary>
        internal static string 请输入正确的金额 {
            get {
                return ResourceManager.GetString("请输入正确的金额", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入离开日期 的本地化字符串。
        /// </summary>
        internal static string 请输入离开日期 {
            get {
                return ResourceManager.GetString("请输入离开日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入线路名称 的本地化字符串。
        /// </summary>
        internal static string 请输入线路名称 {
            get {
                return ResourceManager.GetString("请输入线路名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string 请选择 {
            get {
                return ResourceManager.GetString("请选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一行数据 的本地化字符串。
        /// </summary>
        internal static string 请选择一行数据 {
            get {
                return ResourceManager.GetString("请选择一行数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择供应商 的本地化字符串。
        /// </summary>
        internal static string 请选择供应商 {
            get {
                return ResourceManager.GetString("请选择供应商", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择国家 的本地化字符串。
        /// </summary>
        internal static string 请选择国家 {
            get {
                return ResourceManager.GetString("请选择国家", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择城市 的本地化字符串。
        /// </summary>
        internal static string 请选择城市 {
            get {
                return ResourceManager.GetString("请选择城市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择线路区域 的本地化字符串。
        /// </summary>
        internal static string 请选择线路区域 {
            get {
                return ResourceManager.GetString("请选择线路区域", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 财务管理 的本地化字符串。
        /// </summary>
        internal static string 财务管理 {
            get {
                return ResourceManager.GetString("财务管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物 的本地化字符串。
        /// </summary>
        internal static string 购物 {
            get {
                return ResourceManager.GetString("购物", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物点 的本地化字符串。
        /// </summary>
        internal static string 购物点 {
            get {
                return ResourceManager.GetString("购物点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用结算单 的本地化字符串。
        /// </summary>
        internal static string 费用结算单 {
            get {
                return ResourceManager.GetString("费用结算单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赠送 的本地化字符串。
        /// </summary>
        internal static string 赠送 {
            get {
                return ResourceManager.GetString("赠送", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路线规划结果 的本地化字符串。
        /// </summary>
        internal static string 路线 {
            get {
                return ResourceManager.GetString("路线", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路线规划查询条件设定有误 的本地化字符串。
        /// </summary>
        internal static string 路线规划查询条件设定有误 {
            get {
                return ResourceManager.GetString("路线规划查询条件设定有误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string 选择 {
            get {
                return ResourceManager.GetString("选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择供应商 的本地化字符串。
        /// </summary>
        internal static string 选择供应商 {
            get {
                return ResourceManager.GetString("选择供应商", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择城市 的本地化字符串。
        /// </summary>
        internal static string 选择城市 {
            get {
                return ResourceManager.GetString("选择城市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择景点 的本地化字符串。
        /// </summary>
        internal static string 选择景点 {
            get {
                return ResourceManager.GetString("选择景点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择景点价格 的本地化字符串。
        /// </summary>
        internal static string 选择景点价格 {
            get {
                return ResourceManager.GetString("选择景点价格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择物品 的本地化字符串。
        /// </summary>
        internal static string 选择物品 {
            get {
                return ResourceManager.GetString("选择物品", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择菜单 的本地化字符串。
        /// </summary>
        internal static string 选择菜单 {
            get {
                return ResourceManager.GetString("选择菜单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择酒店 的本地化字符串。
        /// </summary>
        internal static string 选择酒店 {
            get {
                return ResourceManager.GetString("选择酒店", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择餐馆 的本地化字符串。
        /// </summary>
        internal static string 选择餐馆 {
            get {
                return ResourceManager.GetString("选择餐馆", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选用 的本地化字符串。
        /// </summary>
        internal static string 选用 {
            get {
                return ResourceManager.GetString("选用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件接收方地址 的本地化字符串。
        /// </summary>
        internal static string 邮件接收方地址 {
            get {
                return ResourceManager.GetString("邮件接收方地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店 的本地化字符串。
        /// </summary>
        internal static string 酒店 {
            get {
                return ResourceManager.GetString("酒店", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店名称 的本地化字符串。
        /// </summary>
        internal static string 酒店名称 {
            get {
                return ResourceManager.GetString("酒店名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店星级要求 的本地化字符串。
        /// </summary>
        internal static string 酒店星级要求 {
            get {
                return ResourceManager.GetString("酒店星级要求", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复密码 的本地化字符串。
        /// </summary>
        internal static string 重复密码 {
            get {
                return ResourceManager.GetString("重复密码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        internal static string 金额 {
            get {
                return ResourceManager.GetString("金额", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门市价 的本地化字符串。
        /// </summary>
        internal static string 门市价 {
            get {
                return ResourceManager.GetString("门市价", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏TO 的本地化字符串。
        /// </summary>
        internal static string 隐藏TO {
            get {
                return ResourceManager.GetString("隐藏TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏表格 的本地化字符串。
        /// </summary>
        internal static string 隐藏表格 {
            get {
                return ResourceManager.GetString("隐藏表格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏页眉 的本地化字符串。
        /// </summary>
        internal static string 隐藏页眉 {
            get {
                return ResourceManager.GetString("隐藏页眉", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏页脚 的本地化字符串。
        /// </summary>
        internal static string 隐藏页脚 {
            get {
                return ResourceManager.GetString("隐藏页脚", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页眉图片 的本地化字符串。
        /// </summary>
        internal static string 页眉图片 {
            get {
                return ResourceManager.GetString("页眉图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页脚图片 的本地化字符串。
        /// </summary>
        internal static string 页脚图片 {
            get {
                return ResourceManager.GetString("页脚图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 的本地化字符串。
        /// </summary>
        internal static string 项目 {
            get {
                return ResourceManager.GetString("项目", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领队 的本地化字符串。
        /// </summary>
        internal static string 领队 {
            get {
                return ResourceManager.GetString("领队", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风味餐 的本地化字符串。
        /// </summary>
        internal static string 风味餐 {
            get {
                return ResourceManager.GetString("风味餐", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 餐厅 的本地化字符串。
        /// </summary>
        internal static string 餐厅 {
            get {
                return ResourceManager.GetString("餐厅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string 首页 {
            get {
                return ResourceManager.GetString("首页", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        internal static string 验证码 {
            get {
                return ResourceManager.GetString("验证码", resourceCulture);
            }
        }
    }
}
